[package]
name = "rich-strong-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rich-strong-lib = "0.1.0"
[patch.crates-io]
rich-strong-lib = { path = '../rich-strong-lib' }